import { Terminal, ShieldAlert, Key, FileWarning, Cpu, Search, FolderOpen, LucideIcon } from "lucide-react";

export type LinuxEventType = 
  | "All"
  | "System Logs"
  | "Auditd"
  | "Authentication"
  | "File System";

export type LinuxEventDef = {
  id: string;
  type: LinuxEventType;
  name: string;
  description: string;
  fields: string[];
  maliciousUse: string;
  mitre: string[];
  icon: LucideIcon;
  color: string;
};

export const LINUX_EVENTS_DB: LinuxEventDef[] = [
  // System Logs
  { id: "syslog", type: "System Logs", name: "System Daemons Log (/var/log/syslog)", description: "The general system logging file for Ubuntu/Debian based systems (or /var/log/messages on RHEL). It captures logs from system daemons, kernel, and various services.", fields: ["Timestamp", "Hostname", "Daemon/Process", "Message"], maliciousUse: "Detecting anomalous service stops/starts, crashes due to exploits, or attackers echoing empty strings to hide tracks.", mitre: ["T1070.002", "T1543.002"], icon: Terminal, color: "text-zinc-400" },
  { id: "bash_history", type: "System Logs", name: "Command History (~/.bash_history)", description: "Records the command line history of bash shell users. Located in each user's home directory.", fields: ["Command"], maliciousUse: "Tracking attacker actions post-compromise. Attackers often run 'history -c' or delete this file to evade detection.", mitre: ["T1059.004", "T1070.003"], icon: Terminal, color: "text-zinc-400" },

  // Authentication
  { id: "auth.log", type: "Authentication", name: "Authentication Logs (/var/log/auth.log)", description: "Records all authentication-related events, including SSH logins, sudo executions, and PAM authentications (or /var/log/secure on RHEL).", fields: ["Timestamp", "Hostname", "Process", "Message (User, IP, Success/Fail)"], maliciousUse: "Detecting SSH brute force attacks, unauthorized root access, or anomalous remote logins.", mitre: ["T1110.001", "T1078", "T1021.004"], icon: Key, color: "text-pink-400" },

  // Auditd
  { id: "auditd EXECVE", type: "Auditd", name: "Command Execution (EXECVE)", description: "Generated by the Linux Audit Daemon when a process executes a new program (execve system call). It captures the full command line arguments.", fields: ["type=EXECVE", "argc", "a0, a1, a2 (Arguments)", "pid", "uid"], maliciousUse: "Detecting the execution of malicious scripts, LOLBins (like curl, wget, python), and interactive reverse shells.", mitre: ["T1059.004", "T1204.002"], icon: Cpu, color: "text-blue-400" },
  { id: "auditd USER_LOGIN", type: "Auditd", name: "User Authentication (USER_LOGIN)", description: "Generated when a user attempts to log into the system.", fields: ["type=USER_LOGIN", "auid", "uid", "res (Success/Failed)"], maliciousUse: "Tracking successful and failed logins to identify brute force or compromised accounts.", mitre: ["T1110", "T1078"], icon: Key, color: "text-pink-400" },
  { id: "auditd USER_CMD", type: "Auditd", name: "Sudo Command (USER_CMD)", description: "Generated when a user executes a command via sudo.", fields: ["type=USER_CMD", "uid", "cmd", "res"], maliciousUse: "Monitoring privilege escalation attempts and tracking what commands an attacker runs as root.", mitre: ["T1548.003"], icon: ShieldAlert, color: "text-red-500" },
  { id: "auditd SYSCALL", type: "Auditd", name: "System Call (SYSCALL)", description: "The base record for any audited system call (open, read, write, connect, etc). Used in conjunction with other records.", fields: ["type=SYSCALL", "syscall", "success", "exit", "pid", "uid", "comm", "exe"], maliciousUse: "Detecting unauthorized file access (e.g. reading /etc/shadow), network connections from unusual binaries, or modifying critical config files.", mitre: ["T1003.008", "T1505.003", "T1543.002", "T1486"], icon: FileWarning, color: "text-yellow-500" }
];
