export type ToolDefinition = {
  id: string;
  name: string;
  description: string;
  category: string;
  path: string;
  keywords: string[];
  aliases?: string[];
  technologies?: string[];
  vendors?: string[];
  offline?: boolean; // True if the tool processes everything locally
};

export const CATEGORIES = [
  "NETWORKING",
  "CYBERSECURITY / BLUE TEAM",
  "SYSADMIN / INFRASTRUCTURE",
  "DEVOPS",
  "DEVELOPMENT",
  "CRYPTOGRAPHY",
  "ENCODING / DECODING",
  "TEXT",
  "OTHER TOOLS"
] as const;

export type Category = typeof CATEGORIES[number];

export const toolsRegistry: ToolDefinition[] = [
  // ==========================================
  // NETWORKING
  // ==========================================
  {
    id: "network-diagram",
    name: "Network Diagram Generator",
    description: "Create, edit and export network topology diagrams interactively.",
    category: "NETWORKING",
    path: "/tools/network/diagram",
    keywords: ["diagram", "topology", "network", "map", "react flow", "canvas", "architecture", "nodes"],
    aliases: ["Topology Map", "Network Architect"],
    technologies: ["React Flow", "Topology"],
    vendors: [],
    offline: true,
  },
  {
    id: "subnet-calculator",
    name: "Subnetting Calculator",
    description: "Calculate network addresses, broadcast, ranges, and wildcard masks.",
    category: "NETWORKING",
    path: "/tools/network/subnet",
    keywords: ["subnet", "cidr", "mask", "network", "broadcast", "ip", "wildcard", "inverse mask"],
    aliases: ["IP Calculator", "Wildcard Calculator"],
    technologies: ["IPv4", "Networking"],
    vendors: ["Cisco", "MikroTik", "Juniper"],
    offline: true,
  },
  {
    id: "ipv6-calculator",
    name: "IPv6 Calculator",
    description: "Expand, compress, and calculate IPv6 subnets and network ranges.",
    category: "NETWORKING",
    path: "/tools/network/ipv6",
    keywords: ["ipv6", "subnet", "prefix", "compress", "expand", "ip", "network"],
    aliases: ["IPv6 Subnet Calculator", "IPv6 Formatter"],
    technologies: ["IPv6", "Networking"],
    offline: true,
  },
  {
    id: "interface-generator",
    name: "Interface Config Generator",
    description: "Generate network interface configurations for Cisco, MikroTik, and FortiGate.",
    category: "NETWORKING",
    path: "/tools/network/interface-generator",
    keywords: ["interface", "config", "ip", "cisco", "mikrotik", "fortigate", "router", "switch", "generate"],
    aliases: ["Interface Config Builder", "Router Interface Config"],
    technologies: ["Networking", "CLI"],
    vendors: ["Cisco", "MikroTik", "Fortinet"],
    offline: true,
  },
  {
    id: "vlan-tool",
    name: "VLAN Calculator & Config",
    description: "Calculate VLAN ranges and generate 802.1Q access/trunk port configurations.",
    category: "NETWORKING",
    path: "/tools/network/vlan",
    keywords: ["vlan", "802.1q", "trunk", "access", "port", "switch", "native", "tagged", "untagged"],
    aliases: ["VLAN Config Generator", "Switchport Builder"],
    technologies: ["Ethernet", "VLAN"],
    vendors: ["Cisco", "MikroTik", "Fortinet"],
    offline: true,
  },
  {
    id: "mtu-mss-calculator",
    name: "MTU / MSS Calculator",
    description: "Calculate Effective MTU and TCP MSS based on network encapsulation.",
    category: "NETWORKING",
    path: "/tools/network/mtu",
    keywords: ["mtu", "mss", "tcp", "payload", "overhead", "encapsulation", "gre", "ipsec", "pppoe", "vlan", "jumbo"],
    aliases: ["MSS Calculator", "MTU Overhead"],
    technologies: ["TCP/IP", "Networking"],
    offline: true,
  },
  {
    id: "bandwidth-calculator",
    name: "Bandwidth Calculator",
    description: "Calculate file transfer times and analyze the impact of latency (RTT) on TCP throughput.",
    category: "NETWORKING",
    path: "/tools/network/bandwidth",
    keywords: ["bandwidth", "transfer", "time", "speed", "throughput", "tcp window", "rtt", "latency", "bottleneck"],
    aliases: ["Transfer Time Calculator", "TCP Throughput"],
    technologies: ["TCP", "Networking"],
    offline: true,
  },
  {
    id: "vlsm-calculator",
    name: "VLSM Calculator",
    description: "Variable Length Subnet Masking calculator to divide a network into subnets of different sizes.",
    category: "NETWORKING",
    path: "/tools/network/vlsm",
    keywords: ["vlsm", "subnet", "mask", "variable length", "ip", "divide", "split"],
    aliases: ["VLSM", "Subnet Splitter"],
    technologies: ["IPv4", "Networking"],
    offline: true,
  },
  {
    id: "cidr-converter",
    name: "CIDR Converter",
    description: "Convert between CIDR notation (e.g. /24) and subnet mask (e.g. 255.255.255.0).",
    category: "NETWORKING",
    path: "/tools/network/cidr",
    keywords: ["cidr", "mask", "prefix", "notation", "routing"],
    aliases: ["Prefix Calculator", "Subnet Mask Converter"],
    technologies: ["IPv4", "Networking"],
    offline: true,
  },
  {
    id: "ip-converter",
    name: "IP to Bin/Hex",
    description: "Convert IPv4 addresses between decimal, binary, and hexadecimal formats.",
    category: "NETWORKING",
    path: "/tools/network/ip-converter",
    keywords: ["ip", "binary", "hex", "decimal", "convert", "format"],
    aliases: ["IP Converter", "Binary IP"],
    technologies: ["IPv4"],
    offline: true,
  },
  {
    id: "mac-validator",
    name: "MAC Validator",
    description: "Validate MAC addresses and find OUI / Vendor information.",
    category: "NETWORKING",
    path: "/tools/network/mac",
    keywords: ["mac", "address", "oui", "vendor", "hardware", "nic", "ethernet", "validate", "format"],
    aliases: ["MAC Lookup", "OUI Lookup"],
    technologies: ["Ethernet", "Networking"],
    offline: true,
  },
  {
    id: "command-reference",
    name: "Cross-Vendor Command Reference",
    description: "Translate operational intents into the exact CLI commands for Cisco, MikroTik, FortiGate, and Linux.",
    category: "NETWORKING",
    path: "/tools/network/command-reference",
    keywords: ["command", "cli", "reference", "cisco", "mikrotik", "fortigate", "linux", "routing", "firewall", "cheat sheet"],
    aliases: ["CLI Translator", "Command Cheat Sheet"],
    technologies: ["CLI", "Networking"],
    vendors: ["Cisco", "MikroTik", "Fortinet", "Linux"],
    offline: true,
  },

  // ==========================================
  // CYBERSECURITY / BLUE TEAM
  // ==========================================
  {
    id: "mitre-reference",
    name: "MITRE ATT&CK Reference",
    description: "Search and reference common MITRE ATT&CK tactics, techniques, and procedures (TTPs).",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/mitre",
    keywords: ["mitre", "att&ck", "tactics", "techniques", "ttp", "threat", "actor", "apt"],
    aliases: ["MITRE Framework", "TTP Lookup"],
    technologies: ["MITRE"],
    offline: true,
  },
  {
    id: "windows-events",
    name: "Windows Events Reference",
    description: "Search and reference Windows Security and Sysmon Event IDs.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/windows-events",
    keywords: ["windows", "events", "sysmon", "telemetry", "logs", "security"],
    aliases: ["Windows Event Viewer", "Sysmon Reference"],
    technologies: ["Windows", "Sysmon"],
    offline: true,
  },
  {
    id: "linux-events",
    name: "Linux Telemetry Reference",
    description: "Search and reference Linux Logs and Auditd Records.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/linux-events",
    keywords: ["linux", "events", "auditd", "telemetry", "logs", "security", "syslog", "auth"],
    aliases: ["Linux Audit Reference", "Auditd Reference"],
    technologies: ["Linux", "Auditd"],
    offline: true,
  },
  {
    id: "incident-report",
    name: "Incident Report Generator",
    description: "Create structured IT and cybersecurity incident reports from raw notes, logs, and timelines.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/incident-report",
    keywords: ["incident", "report", "outage", "postmortem", "documentation", "ticket", "rca", "root cause", "timeline"],
    aliases: ["Postmortem Builder", "RCA Generator"],
    technologies: ["Incident Response", "Documentation"],
    offline: true,
  },
  {
    id: "mitre-simulator",
    name: "MITRE ATT&CK Simulator",
    description: "Interactive incident response simulator. Map real attack scenarios to MITRE techniques and Windows Event IDs.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/mitre-simulator",
    keywords: ["mitre", "att&ck", "simulator", "game", "incident", "response", "ctf", "practice", "mapping", "event id", "sysmon"],
    aliases: ["Incident Response Game", "TTP Mapper"],
    technologies: ["MITRE", "Sysmon"],
    offline: true,
  },
  {
    id: "acl-builder",
    name: "Universal ACL Builder",
    description: "Create firewall rules and compile to Cisco, MikroTik, or FortiGate",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/acl-builder",
    keywords: ["acl", "firewall", "rule", "policy", "cisco", "mikrotik", "fortigate", "permit", "deny"],
    aliases: ["Firewall Policy Generator", "Access Control List Builder"],
    technologies: ["Firewall", "Security"],
    vendors: ["Cisco", "MikroTik", "Fortinet"],
    offline: true,
  },
  {
    id: "acl-simulator",
    name: "ACL Simulator",
    description: "Test your ACL rules by simulating packet injection against a firewall.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/acl-simulator",
    keywords: ["acl", "simulator", "packet", "test", "firewall", "match", "tracer", "drop", "allow"],
    aliases: ["Firewall Rule Tester", "Packet Matcher"],
    technologies: ["Security", "Networking"],
    offline: true,
  },
  {
    id: "nat-generator",
    name: "NAT Generator",
    description: "Generate Source NAT (Masquerade) and Destination NAT (Port Forwarding) rules.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/nat-generator",
    keywords: ["nat", "dnat", "snat", "port forwarding", "masquerade", "mikrotik", "fortigate", "iptables"],
    aliases: ["Port Forward Generator", "Source NAT Builder"],
    technologies: ["Networking", "NAT"],
    vendors: ["MikroTik", "Fortinet", "Linux"],
    offline: true,
  },
  {
    id: "headers-scorecard",
    name: "Headers & TLS Scorecard",
    description: "Analyze HTTP security headers and TLS configuration of any public website.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/scorecard",
    keywords: ["security", "headers", "tls", "ssl", "https", "hsts", "csp", "x-frame-options", "audit"],
    aliases: ["Security Scorecard", "Header Analyzer"],
    technologies: ["HTTP", "TLS", "Web"],
    offline: false, // Requires internet to scan
  },
  {
    id: "log-parser",
    name: "Local Log Parser",
    description: "Extract IPs, emails, and IOCs from logs without uploading them anywhere.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/log-parser",
    keywords: ["log", "parse", "extract", "ioc", "ip", "email", "syslog", "apache", "nginx", "regex"],
    aliases: ["IOC Extractor", "Log Analyzer"],
    technologies: ["Linux", "Syslog", "Apache", "Nginx", "SIEM"],
    offline: true,
  },
  {
    id: "pcap-analyzer",
    name: "PCAP Analyzer",
    description: "Analyze packet captures and flows directly in the browser.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/pcap",
    keywords: ["pcap", "packet", "capture", "wireshark", "tcpdump", "network", "flow", "traffic"],
    aliases: ["Packet Analyzer", "Wireshark Online"],
    technologies: ["TCP/IP", "PCAP"],
    offline: true,
  },
  {
    id: "url-defanger",
    name: "URL Defanger",
    description: "Defang IOCs and decode corporate Safelinks (Microsoft, Proofpoint) for incident reports.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/defanger",
    keywords: ["defang", "refang", "url", "safelink", "proofpoint", "ioc", "phishing", "malware", "hxxp"],
    aliases: ["Safelink Decoder", "IOC Defanger"],
    technologies: ["Phishing", "Email Security"],
    vendors: ["Microsoft", "Proofpoint"],
    offline: true,
  },
  {
    id: "magic-bytes",
    name: "File Magic Bytes Detector",
    description: "Detect the true file type of any file by analyzing its hexadecimal signature.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/magic-bytes",
    keywords: ["magic bytes", "hex", "signature", "file type", "spoof", "detect", "malware", "analysis"],
    aliases: ["Hex Signature Reader", "True File Type"],
    technologies: ["Forensics", "DFIR"],
    offline: true,
  },
  {
    id: "exif-analyzer",
    name: "EXIF Analyzer & Cleaner",
    description: "Extract hidden metadata from images or scrub it entirely for privacy.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/exif",
    keywords: ["exif", "metadata", "image", "photo", "gps", "camera", "clean", "scrub", "remove", "privacy"],
    aliases: ["Metadata Extractor", "EXIF Remover"],
    technologies: ["Forensics", "OSINT"],
    offline: true,
  },
  {
    id: "x509-analyzer",
    name: "X.509 Certificate Analyzer",
    description: "Parse and decode PEM certificates to view Issuer, Subject, SANs, and Validity.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/x509",
    keywords: ["x509", "certificate", "pem", "decode", "parse", "ssl", "tls", "issuer", "subject", "validity"],
    aliases: ["PEM Decoder", "Certificate Viewer"],
    technologies: ["PKI", "TLS/SSL"],
    offline: true,
  },
  {
    id: "log-timeline",
    name: "Log Timeline Generator",
    description: "Sort raw logs chronologically and generate a visual timeline of events.",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/log-timeline",
    keywords: ["log", "timeline", "sort", "chronological", "event", "time", "investigation", "incident", "response"],
    aliases: ["Event Timeline", "Chronological Sorter"],
    technologies: ["DFIR", "SIEM"],
    offline: true,
  },
  {
    id: "hibp-check",
    name: "HIBP Password Checker",
    description: "Check if a password was breached without sending it, using k-anonymity (SHA-1 prefix).",
    category: "CYBERSECURITY / BLUE TEAM",
    path: "/tools/security/hibp",
    keywords: ["password", "breach", "hibp", "pwned", "have i been pwned", "security", "k-anonymity", "hash"],
    aliases: ["Breach Checker", "Password Tester"],
    technologies: ["Cryptography", "Web"],
    offline: false, // Requires calling the HIBP API
  },

  // ==========================================
  // SYSADMIN / INFRASTRUCTURE
  // ==========================================
  {
    id: "runbook-builder",
    name: "Interactive Runbook Builder",
    description: "Build and execute IT operations and troubleshooting runbooks dynamically.",
    category: "SYSADMIN / INFRASTRUCTURE",
    path: "/tools/sysadmin/runbook",
    keywords: ["runbook", "playbook", "troubleshooting", "sop", "procedure", "checklist"],
    aliases: ["SOP Builder", "Playbook Engine"],
    technologies: ["JSON", "Markdown"],
    offline: true,
  },
  {
    id: "raid-calculator",
    name: "RAID Calculator",
    description: "Calculate usable capacity, fault tolerance, and theoretical performance for RAID arrays.",
    category: "SYSADMIN / INFRASTRUCTURE",
    path: "/tools/sysadmin/raid",
    keywords: ["raid", "storage", "capacity", "fault", "tolerance", "disk", "array", "0", "1", "5", "6", "10"],
    aliases: ["Disk Array Calculator"],
    technologies: ["Storage", "Hardware"],
    offline: true,
  },
  {
    id: "ups-calculator",
    name: "UPS Runtime Calculator",
    description: "Calculate estimated battery backup time for your server rack or network equipment.",
    category: "SYSADMIN / INFRASTRUCTURE",
    path: "/tools/sysadmin/ups",
    keywords: ["ups", "battery", "runtime", "power", "watt", "va", "backup", "apc", "cyberpower"],
    aliases: ["Battery Runtime", "Power Calculator"],
    technologies: ["Hardware", "Power"],
    offline: true,
  },
  {
    id: "backup-calculator",
    name: "Backup Window Calculator",
    description: "Calculate backup transfer times and estimate total storage capacity needed based on retention.",
    category: "SYSADMIN / INFRASTRUCTURE",
    path: "/tools/sysadmin/backup",
    keywords: ["backup", "time", "window", "storage", "retention", "transfer", "speed", "incremental", "full"],
    aliases: ["Backup Speed", "Storage Estimator"],
    technologies: ["Storage", "Backup"],
    offline: true,
  },
  {
    id: "systemd-generator",
    name: "Systemd Service Generator",
    description: "Visually construct a Linux systemd .service file to easily daemonize your scripts and apps.",
    category: "SYSADMIN / INFRASTRUCTURE",
    path: "/tools/sysadmin/systemd",
    keywords: ["systemd", "service", "daemon", "linux", "unit", "start", "stop", "restart", "systemctl"],
    aliases: ["Service File Builder", "Daemon Generator"],
    technologies: ["Linux", "Unix"],
    offline: true,
  },
  {
    id: "storage-calculator",
    name: "Storage Calculator",
    description: "Convert between Decimal (GB, TB) and Binary (GiB, TiB) storage units to understand true disk capacity.",
    category: "SYSADMIN / INFRASTRUCTURE",
    path: "/tools/sysadmin/storage",
    keywords: ["storage", "disk", "capacity", "tb", "tib", "gb", "gib", "convert", "binary", "decimal", "size"],
    aliases: ["Terabyte to Tebibyte", "Disk Size Calculator"],
    technologies: ["Storage"],
    offline: true,
  },
  {
    id: "rpo-rto-calculator",
    name: "RPO / RTO Calculator",
    description: "Visualize the business impact of your Disaster Recovery plan by calculating Recovery Point Objective and Recovery Time Objective.",
    category: "SYSADMIN / INFRASTRUCTURE",
    path: "/tools/sysadmin/rpo-rto",
    keywords: ["rpo", "rto", "disaster", "recovery", "downtime", "loss", "backup", "business continuity", "bcdr"],
    aliases: ["Disaster Recovery Calculator", "Downtime Estimator"],
    technologies: ["Storage", "Backup", "Security"],
    offline: true,
  },

  // ==========================================
  // DEVOPS
  // ==========================================
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Linux file permissions using an interactive visual grid.",
    category: "DEVOPS",
    path: "/tools/devops/chmod",
    keywords: ["chmod", "permissions", "linux", "unix", "owner", "group", "public", "rwx", "octal"],
    aliases: ["Permission Calculator", "Linux Permissions"],
    technologies: ["Linux", "Unix"],
    offline: true,
  },
  {
    id: "docker-converter",
    name: "Docker Converter",
    description: "Convert docker run commands to docker-compose.yml files.",
    category: "DEVOPS",
    path: "/tools/devops/docker",
    keywords: ["docker", "compose", "run", "container", "yaml", "yml", "convert"],
    aliases: ["Docker Compose Builder", "Docker Run Parser"],
    technologies: ["Docker", "Containers"],
    offline: true,
  },

  // ==========================================
  // CRYPTOGRAPHY
  // ==========================================
  {
    id: "hash-generators",
    name: "Hash Generators",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes from text.",
    category: "CRYPTOGRAPHY",
    path: "/tools/crypto/hash",
    keywords: ["hash", "md5", "sha1", "sha256", "sha512", "digest", "text", "crypto"],
    aliases: ["Text Hasher"],
    technologies: ["Cryptography"],
    offline: true,
  },
  {
    id: "file-hash-analyzer",
    name: "File Hash Analyzer",
    description: "Verify file integrity with MD5/SHA. Processes heavy files locally via native WebCrypto.",
    category: "CRYPTOGRAPHY",
    path: "/tools/crypto/file-hash",
    keywords: ["hash", "file", "md5", "sha1", "sha256", "sha512", "checksum", "integrity", "iso", "verify"],
    aliases: ["File Checksum", "File Hasher"],
    technologies: ["Cryptography"],
    offline: true,
  },
  {
    id: "password-gen-audit",
    name: "Password Gen & Audit",
    description: "Generate strong passwords and audit their entropy and crack time locally.",
    category: "CRYPTOGRAPHY",
    path: "/tools/crypto/password",
    keywords: ["password", "generator", "audit", "zxcvbn", "entropy", "security", "strength"],
    aliases: ["Password Generator", "Password Strength"],
    technologies: ["Security"],
    offline: true,
  },
  {
    id: "uuid-ulid",
    name: "UUID/ULID Generator",
    description: "Generate Universally Unique Identifiers (UUID) and Universally Unique Lexicographically Sortable Identifiers (ULID).",
    category: "DEVELOPMENT",
    path: "/tools/crypto/uuid",
    keywords: ["uuid", "ulid", "guid", "generate", "unique", "identifier"],
    aliases: ["GUID Generator"],
    technologies: ["Database", "Development"],
    offline: true,
  },

  // ==========================================
  // ENCODING / DECODING
  // ==========================================
  {
    id: "base64-encoder",
    name: "Base64 Encoder",
    description: "Encode and decode text to/from Base64 format.",
    category: "ENCODING / DECODING",
    path: "/tools/encoding/base64",
    keywords: ["base64", "encode", "decode", "text", "format"],
    aliases: ["Base64 Converter"],
    offline: true,
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    description: "Encode and decode URLs and query parameters.",
    category: "ENCODING / DECODING",
    path: "/tools/encoding/url",
    keywords: ["url", "uri", "encode", "decode", "percent", "escape"],
    aliases: ["URI Encoder"],
    technologies: ["Web"],
    offline: true,
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between Binary, Octal, Decimal, and Hexadecimal.",
    category: "ENCODING / DECODING",
    path: "/tools/encoding/number-base",
    keywords: ["number", "base", "binary", "octal", "decimal", "hexadecimal", "hex", "convert"],
    aliases: ["Hex Converter", "Binary Converter"],
    offline: true,
  },
  {
    id: "json-yaml-converter",
    name: "JSON / YAML Converter",
    description: "Convert data between JSON and YAML formats.",
    category: "ENCODING / DECODING",
    path: "/tools/encoding/json-yaml",
    keywords: ["json", "yaml", "yml", "convert", "format", "parse"],
    aliases: ["YAML to JSON", "JSON to YAML"],
    technologies: ["JSON", "YAML"],
    offline: true,
  },
  {
    id: "jwt-master",
    name: "JWT Master Tool",
    description: "Decode and inspect JSON Web Tokens (JWT) locally without compromising the signature.",
    category: "ENCODING / DECODING",
    path: "/tools/encoding/jwt",
    keywords: ["jwt", "token", "decode", "inspect", "json web token", "auth", "claims", "header", "payload"],
    aliases: ["JWT Decoder"],
    technologies: ["JWT", "Auth"],
    offline: true,
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix epoch timestamps to human-readable dates, ISO 8601, and local time zones instantly.",
    category: "DEVELOPMENT",
    path: "/tools/encoding/timestamp",
    keywords: ["timestamp", "unix", "epoch", "time", "date", "iso", "iso8601", "utc", "gmt", "timezone", "convert"],
    aliases: ["Unix Time Converter", "Epoch Converter"],
    technologies: ["Development"],
    offline: true,
  },

  // ==========================================
  // DEVELOPMENT
  // ==========================================
  {
    id: "sql-beautifier",
    name: "SQL Beautifier",
    description: "Format and prettify raw or minified SQL queries instantly.",
    category: "DEVELOPMENT",
    path: "/tools/dev/sql-beautifier",
    keywords: ["sql", "beautifier", "formatter", "format", "query", "database", "mysql", "postgresql"],
    aliases: ["SQL Formatter"],
    technologies: ["Database", "SQL"],
    offline: true,
  },
  {
    id: "sql-minifier",
    name: "SQL Minifier",
    description: "Compress SQL queries into a single line by removing unnecessary whitespace and comments.",
    category: "DEVELOPMENT",
    path: "/tools/dev/sql-minifier",
    keywords: ["sql", "minifier", "minify", "compress", "query", "database"],
    aliases: ["SQL Compressor"],
    technologies: ["Database", "SQL"],
    offline: true,
  },
  {
    id: "gitignore-generator",
    name: ".gitignore Generator",
    description: "Create useful .gitignore files for your project instantly. 100% offline.",
    category: "DEVELOPMENT",
    path: "/tools/dev/gitignore",
    keywords: ["git", "gitignore", "generator", "ignore", "repo", "repository", "templates"],
    aliases: ["Git Ignore"],
    technologies: ["Git", "Version Control"],
    offline: true,
  },

  // ==========================================
  // TEXT
  // ==========================================
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions against text in real-time.",
    category: "TEXT",
    path: "/tools/text/regex",
    keywords: ["regex", "regular expression", "match", "test", "pattern", "pcre", "javascript"],
    aliases: ["Regex Matcher"],
    technologies: ["Regex"],
    offline: true,
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare two blocks of text and find the differences.",
    category: "TEXT",
    path: "/tools/text/diff",
    keywords: ["diff", "compare", "difference", "text", "changes", "compare files"],
    aliases: ["File Compare"],
    offline: true,
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Beautify and format JSON strings with syntax highlighting.",
    category: "TEXT",
    path: "/tools/text/json",
    keywords: ["json", "format", "beautify", "pretty", "minify", "parse", "validate"],
    aliases: ["JSON Beautifier", "JSON Validator"],
    technologies: ["JSON"],
    offline: true,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count characters, words, lines, and bytes in a text.",
    category: "TEXT",
    path: "/tools/text/counter",
    keywords: ["word", "character", "count", "lines", "length", "size", "bytes"],
    aliases: ["Character Counter"],
    offline: true,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Generate placeholder lorem ipsum text.",
    category: "TEXT",
    path: "/tools/text/lorem",
    keywords: ["lorem", "ipsum", "placeholder", "text", "generate", "dummy"],
    aliases: ["Text Generator"],
    offline: true,
  },

  // ==========================================
  // OTHER TOOLS
  // ==========================================
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Parse cron expressions and translate them to human readable text.",
    category: "OTHER TOOLS",
    path: "/tools/other/cron",
    keywords: ["cron", "schedule", "parser", "crontab", "time", "human"],
    aliases: ["Crontab Generator", "Cron Explainer"],
    technologies: ["Linux", "Unix"],
    offline: true,
  },
  {
    id: "qr-code",
    name: "QR Code Generator",
    description: "Generate highly customizable QR codes.",
    category: "OTHER TOOLS",
    path: "/tools/other/qr",
    keywords: ["qr", "code", "generate", "barcode", "2d", "image", "wifi"],
    aliases: ["QR Generator"],
    offline: true,
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, HSL, and CMYK formats.",
    category: "OTHER TOOLS",
    path: "/tools/other/color",
    keywords: ["color", "hex", "rgb", "hsl", "cmyk", "convert", "css"],
    aliases: ["CSS Color Converter"],
    technologies: ["CSS", "Web"],
    offline: true,
  }
];
