import { Terminal, ShieldAlert, Monitor, Key, FileWarning, Search, Cpu, FolderOpen } from "lucide-react";
import { LucideIcon } from "lucide-react";

export type WinEventType = 
  | "All"
  | "Process Creation" 
  | "Process Lifecycle"
  | "Network Connection" 
  | "File System" 
  | "Registry" 
  | "Interprocess Communication"
  | "Authentication" 
  | "System"
  | "Object Access";

export type WinEventDef = {
  id: string;
  type: WinEventType;
  name: string;
  description: string;
  fields: string[];
  maliciousUse: string;
  mitre: string[];
  icon: LucideIcon;
  color: string;
};

export const WIN_EVENTS_DB: WinEventDef[] = [
  // Process Creation
  { id: "Sysmon 1", type: "Process Creation", name: "Process Creation", description: "Provides detailed information about newly created processes. It is equivalent to Windows Event 4688 but includes the command line and parent-child process relationships.", fields: ["Image", "CommandLine", "ParentImage", "Hashes", "User"], maliciousUse: "Detecting execution of malicious payloads, LOLBins like PowerShell or cmd.exe, and suspicious parent-child chains (e.g. Word spawning cmd.exe).", mitre: ["T1059.001", "T1059.003", "T1204.002", "T1566.001"], icon: Cpu, color: "text-blue-400" },
  { id: "4688", type: "Process Creation", name: "A new process has been created", description: "Generated every time a new process starts. Requires Command Line auditing to be enabled via GPO for full visibility.", fields: ["New Process Name", "Creator Process ID", "Process Command Line"], maliciousUse: "Tracking attacker execution and lateral movement tools.", mitre: ["T1059.001", "T1059.003", "T1204.002"], icon: Cpu, color: "text-blue-400" },
  { id: "Sysmon 2", type: "File System", name: "File Creation Time Changed", description: "Records a process explicitly changing a file creation timestamp. This can be legitimate, but it is valuable for detecting timestomping and timeline manipulation.", fields: ["Image", "TargetFilename", "CreationUtcTime", "PreviousCreationUtcTime", "User"], maliciousUse: "Detecting attempts to make a backdoor or tool appear older than it is.", mitre: ["T1070.006"], icon: FileWarning, color: "text-yellow-500" },
  { id: "Sysmon 4", type: "System", name: "Sysmon Service State Changed", description: "Records the Sysmon service starting or stopping. This event is not filterable and should be correlated with service-control activity.", fields: ["UtcTime", "State"], maliciousUse: "Detecting a telemetry gap created by stopping or restarting Sysmon during an intrusion.", mitre: ["T1562.001"], icon: ShieldAlert, color: "text-red-500" },
  { id: "Sysmon 5", type: "Process Lifecycle", name: "Process Terminated", description: "Records when a process terminates, including its process identity and timestamp.", fields: ["UtcTime", "ProcessGuid", "ProcessId", "Image", "User"], maliciousUse: "Correlating short-lived tools, abnormal termination and process chains during an investigation.", mitre: [], icon: Cpu, color: "text-blue-400" },
  { id: "Sysmon 8", type: "Process Creation", name: "CreateRemoteThread", description: "Detects when a process creates a thread in another process, a common technique for process injection.", fields: ["SourceImage", "TargetImage", "StartAddress", "StartFunction"], maliciousUse: "Identifying process injection techniques like DLL injection or shellcode execution.", mitre: ["T1055.001", "T1055.002"], icon: ShieldAlert, color: "text-red-500" },
  { id: "Sysmon 10", type: "Process Creation", name: "ProcessAccess", description: "Logs when a process opens another process, which is often used for credential dumping or memory reading.", fields: ["SourceImage", "TargetImage", "CallTrace", "GrantedAccess"], maliciousUse: "Detecting credential dumping tools like Mimikatz or procdump targeting LSASS.", mitre: ["T1003.001"], icon: ShieldAlert, color: "text-red-500" },

  // Network Connection
  { id: "Sysmon 3", type: "Network Connection", name: "Network Connection", description: "Logs TCP/UDP connections on the machine.", fields: ["Image", "DestinationIp", "DestinationPort", "Protocol"], maliciousUse: "Identifying C2 beaconing, lateral movement via RDP/SMB, or exfiltration.", mitre: ["T1071", "T1570", "T1021.001", "T1021.002"], icon: Monitor, color: "text-indigo-400" },
  { id: "Sysmon 22", type: "Network Connection", name: "DNSEvent (DNS query)", description: "Logs DNS queries, regardless of whether they succeed or fail, and what process performed them.", fields: ["Image", "QueryName", "QueryStatus", "QueryResults"], maliciousUse: "Detecting DNS tunneling, C2 domains, and DGA (Domain Generation Algorithms).", mitre: ["T1071.004", "T1568", "T1568.002"], icon: Monitor, color: "text-indigo-400" },

  // File System
  { id: "Sysmon 11", type: "File System", name: "FileCreate", description: "Logs when a file is created or overwritten.", fields: ["Image", "TargetFilename", "CreationUtcTime"], maliciousUse: "Tracking malware drops, web shell uploads, or ransomware activity.", mitre: ["T1105", "T1505.003", "T1486"], icon: FileWarning, color: "text-yellow-500" },
  { id: "Sysmon 23", type: "File System", name: "FileDelete", description: "Logs when a file is deleted. Can capture the deleted file if configured.", fields: ["Image", "TargetFilename", "Hashes", "IsExecutable"], maliciousUse: "Detecting attackers wiping their tools, clearing logs, or ransomware removing volume shadow copies.", mitre: ["T1070.004", "T1485"], icon: FileWarning, color: "text-yellow-500" },

  // Registry
  { id: "Sysmon 13", type: "Registry", name: "RegistryEvent (Value Set)", description: "Logs registry value modifications.", fields: ["Image", "TargetObject", "Details"], maliciousUse: "Identifying persistence mechanisms (e.g. Run keys) or UAC bypass attempts.", mitre: ["T1547.001", "T1546.012", "T1112"], icon: FolderOpen, color: "text-orange-400" },

  // Authentication
  { id: "4624", type: "Authentication", name: "Logon Success", description: "An account was successfully logged on. Key indicator of valid user activity or compromised accounts.", fields: ["Logon Type", "Account Name", "Source Network Address"], maliciousUse: "Tracking lateral movement via compromised credentials, Pass-the-Hash (Type 3), or RDP (Type 10).", mitre: ["T1078", "T1021.001", "T1021.002", "T1550.002"], icon: Key, color: "text-pink-400" },
  { id: "4625", type: "Authentication", name: "Logon Failure", description: "An account failed to log on. Essential for detecting brute force attacks.", fields: ["Logon Type", "Account Name", "Failure Reason", "Source Network Address"], maliciousUse: "Detecting password spraying or brute force attacks.", mitre: ["T1110.001", "T1110.003"], icon: Key, color: "text-pink-400" },
  { id: "4724", type: "Authentication", name: "Password Reset Attempt", description: "An attempt was made to reset an account's password by an administrator.", fields: ["Target Account Name", "Subject Account Name"], maliciousUse: "Attackers resetting admin passwords to maintain persistent access to a compromised domain.", mitre: ["T1098"], icon: Key, color: "text-pink-400" },

  // System
  { id: "1102", type: "System", name: "Audit Log Cleared", description: "The audit log was cleared. This is highly suspicious if performed outside of regular maintenance.", fields: ["Subject User", "Log Name"], maliciousUse: "Defense evasion. Attackers covering their tracks by wiping the Security Event Log.", mitre: ["T1070.001"], icon: ShieldAlert, color: "text-red-500" },
  { id: "7045", type: "System", name: "Service Installed", description: "A service was installed in the system.", fields: ["Service Name", "Service File Name", "Service Start Type"], maliciousUse: "Detecting persistence via malicious Windows Services.", mitre: ["T1543.003"], icon: Cpu, color: "text-blue-400" },
  { id: "4698", type: "System", name: "Scheduled Task Created", description: "A scheduled task was created.", fields: ["Task Name", "Task Content"], maliciousUse: "Detecting persistence via malicious Scheduled Tasks.", mitre: ["T1053.005"], icon: Cpu, color: "text-blue-400" },

  // Object Access
  { id: "5140", type: "Object Access", name: "Network Share Access", description: "A network share object was accessed.", fields: ["Share Name", "Share Local Path", "Account Name"], maliciousUse: "Tracking lateral movement, access to sensitive shares (e.g. C$, ADMIN$), or data staging.", mitre: ["T1021.002"], icon: Search, color: "text-teal-400" },

  // Additional Security and Sysmon telemetry
  { id: "4103", type: "Process Creation", name: "PowerShell Module Logging", description: "PowerShell module logging records pipeline execution details when the corresponding policy is enabled.", fields: ["Context", "User", "Command", "CommandInvocation", "CommandParameter"], maliciousUse: "Detecting PowerShell execution and suspicious cmdlets that may be missed by process creation alone.", mitre: ["T1059.001"], icon: Terminal, color: "text-blue-400" },
  { id: "4104", type: "Process Creation", name: "PowerShell Script Block Logging", description: "PowerShell script block logging records the contents of executed script blocks, including dynamically generated code.", fields: ["ScriptBlockText", "Path", "User", "MessageNumber", "MessageTotal"], maliciousUse: "Detecting encoded commands, downloaders, credential theft and defense impairment in PowerShell content.", mitre: ["T1059.001", "T1027"], icon: Terminal, color: "text-blue-400" },
  { id: "4689", type: "Process Creation", name: "Process Exit", description: "Records when a process terminates and its exit status.", fields: ["Process ID", "Process Name", "Subject User", "Exit Status"], maliciousUse: "Correlating short-lived tooling, crash loops and process chains with suspicious execution.", mitre: ["T1059"], icon: Cpu, color: "text-blue-400" },
  { id: "Sysmon 6", type: "System", name: "Driver Loaded", description: "Logs when a kernel driver is loaded into a host.", fields: ["ImageLoaded", "Hashes", "Signature", "SignatureStatus", "User"], maliciousUse: "Detecting unsigned or unexpected drivers used for rootkits, credential access or security-tool bypass.", mitre: ["T1014", "T1547.006"], icon: ShieldAlert, color: "text-red-500" },
  { id: "Sysmon 7", type: "Process Creation", name: "Image Loaded", description: "Logs when a process loads a module or image, subject to Sysmon configuration.", fields: ["Image", "ImageLoaded", "Hashes", "Signature", "Signed"], maliciousUse: "Detecting DLL search-order hijacking, unsigned modules and credential API hooking.", mitre: ["T1574.001", "T1056.004"], icon: ShieldAlert, color: "text-red-500" },
  { id: "Sysmon 9", type: "File System", name: "RawAccessRead", description: "Logs when a process performs raw read access to a drive.", fields: ["Image", "Device", "User"], maliciousUse: "Detecting attempts to read disk structures, shadow data or protected files outside normal tooling.", mitre: ["T1003", "T1561"], icon: FileWarning, color: "text-yellow-500" },
  { id: "Sysmon 12", type: "Registry", name: "Registry Object Create/Delete", description: "Logs creation or deletion of registry keys and values.", fields: ["EventType", "Image", "TargetObject", "User"], maliciousUse: "Detecting persistence, configuration tampering and cleanup of registry artifacts.", mitre: ["T1112", "T1547.001"], icon: FolderOpen, color: "text-orange-400" },
  { id: "Sysmon 14", type: "Registry", name: "Registry Key/Value Rename", description: "Logs registry key or value rename operations.", fields: ["EventType", "Image", "TargetObject", "NewName"], maliciousUse: "Detecting registry manipulation intended to alter controls or hide persistence changes.", mitre: ["T1112"], icon: FolderOpen, color: "text-orange-400" },
  { id: "Sysmon 15", type: "File System", name: "FileCreateStreamHash", description: "Logs alternate data stream creation and the associated file hash.", fields: ["Image", "TargetFilename", "Contents", "Hashes"], maliciousUse: "Detecting NTFS alternate data streams used to hide payloads or metadata.", mitre: ["T1564.004"], icon: FileWarning, color: "text-yellow-500" },
  { id: "Sysmon 16", type: "System", name: "Sysmon Configuration Change", description: "Logs changes to the active Sysmon configuration.", fields: ["Configuration", "ConfigurationFileHash", "User"], maliciousUse: "Detecting attempts to reduce endpoint visibility or remove event collection rules.", mitre: ["T1562.001"], icon: ShieldAlert, color: "text-red-500" },
  { id: "Sysmon 17", type: "Interprocess Communication", name: "Pipe Created", description: "Logs named pipe creation by a process.", fields: ["PipeName", "Image", "ProcessId", "User"], maliciousUse: "Detecting inter-process communication used by malware, lateral movement tools and C2 frameworks.", mitre: ["T1559", "T1055"], icon: Monitor, color: "text-indigo-400" },
  { id: "Sysmon 18", type: "Interprocess Communication", name: "Pipe Connected", description: "Logs a process connecting to a named pipe.", fields: ["PipeName", "Image", "ClientProcessId", "ServerProcessId"], maliciousUse: "Correlating named-pipe clients and servers to identify suspicious process injection or remote tooling.", mitre: ["T1559", "T1055"], icon: Monitor, color: "text-indigo-400" },
  { id: "Sysmon 19", type: "System", name: "WMI Event Filter", description: "Logs creation of a WMI event filter subscription.", fields: ["EventNamespace", "Name", "Query", "User"], maliciousUse: "Detecting WMI event subscriptions used for fileless persistence.", mitre: ["T1546.003"], icon: ShieldAlert, color: "text-red-500" },
  { id: "Sysmon 20", type: "System", name: "WMI Event Consumer", description: "Logs creation of a WMI event consumer.", fields: ["Name", "Type", "Destination", "User"], maliciousUse: "Detecting persistent WMI consumers that execute or deliver attacker-controlled content.", mitre: ["T1546.003"], icon: ShieldAlert, color: "text-red-500" },
  { id: "Sysmon 21", type: "System", name: "WMI Consumer to Filter Binding", description: "Logs binding between a WMI event filter and consumer.", fields: ["Consumer", "Filter", "Namespace", "User"], maliciousUse: "Confirming a complete WMI persistence chain rather than an isolated subscription artifact.", mitre: ["T1546.003"], icon: ShieldAlert, color: "text-red-500" },
  { id: "Sysmon 24", type: "File System", name: "Clipboard Change", description: "Logs clipboard content changes when configured, including the process responsible.", fields: ["Session", "ClientInfo", "Image", "Hash"], maliciousUse: "Detecting clipboard theft, token harvesting and suspicious copy/paste activity.", mitre: ["T1115"], icon: FileWarning, color: "text-yellow-500" },
  { id: "Sysmon 25", type: "Process Creation", name: "Process Tampering", description: "Logs process image tampering such as herpaderping or hollowing indicators.", fields: ["Image", "Type", "ProcessId", "User"], maliciousUse: "Detecting attempts to make a malicious process appear to be a trusted image.", mitre: ["T1055", "T1036"], icon: ShieldAlert, color: "text-red-500" },
  { id: "4697", type: "System", name: "Service Installed", description: "Records installation of a service in the system.", fields: ["Service Name", "Service File Name", "Subject User"], maliciousUse: "Detecting service-based persistence and remote execution.", mitre: ["T1543.003", "T1569.002"], icon: Cpu, color: "text-blue-400" },
  { id: "4648", type: "Authentication", name: "Logon Using Explicit Credentials", description: "Records a logon attempt made with explicit credentials while the user is already logged on as a different account.", fields: ["Subject User", "Target User", "Target Server", "Process Name", "Network Address"], maliciousUse: "Detecting runas, lateral movement and credential use outside the normal interactive logon flow.", mitre: ["T1078", "T1550"], icon: Key, color: "text-pink-400" },
  { id: "4672", type: "Authentication", name: "Special Privileges Assigned to New Logon", description: "Records a new logon receiving sensitive privileges such as SeDebugPrivilege or SeImpersonatePrivilege.", fields: ["Subject User", "Subject Domain", "Logon ID", "Privileges"], maliciousUse: "Prioritizing privileged logons and correlating them with unusual source hosts or process creation.", mitre: ["T1078", "T1068"], icon: Key, color: "text-pink-400" },
  { id: "4740", type: "Authentication", name: "User Account Locked Out", description: "Records a domain or local account being locked out after failed authentication attempts.", fields: ["Target Account", "Caller Computer Name", "Subject User"], maliciousUse: "Detecting password spraying, brute force and attempts to disrupt account availability.", mitre: ["T1110", "T1531"], icon: Key, color: "text-pink-400" },
  { id: "4699", type: "System", name: "Scheduled Task Deleted", description: "Records deletion of a scheduled task.", fields: ["Task Name", "Subject User"], maliciousUse: "Detecting cleanup or removal of scheduled-task persistence.", mitre: ["T1053.005", "T1070.004"], icon: Cpu, color: "text-blue-400" },
  { id: "4700", type: "System", name: "Scheduled Task Enabled", description: "Records when a scheduled task is enabled.", fields: ["Task Name", "Subject User"], maliciousUse: "Detecting activation of dormant persistence or scheduled payloads.", mitre: ["T1053.005"], icon: Cpu, color: "text-blue-400" },
  { id: "4702", type: "System", name: "Scheduled Task Updated", description: "Records modification of a scheduled task.", fields: ["Task Name", "Task Content", "Subject User"], maliciousUse: "Detecting replacement of legitimate scheduled actions with attacker-controlled commands.", mitre: ["T1053.005"], icon: Cpu, color: "text-blue-400" },
  { id: "4719", type: "System", name: "System Audit Policy Changed", description: "Records changes to the system audit policy.", fields: ["Category", "Subcategory", "Changes", "Subject User"], maliciousUse: "Detecting attempts to disable or weaken security auditing.", mitre: ["T1562.002"], icon: ShieldAlert, color: "text-red-500" },
  { id: "4720", type: "Authentication", name: "User Account Created", description: "Records creation of a new user account.", fields: ["Target Account", "Subject Account", "Display Name", "Workstation"], maliciousUse: "Detecting unauthorized persistence accounts and suspicious account creation bursts.", mitre: ["T1136.001"], icon: Key, color: "text-pink-400" },
  { id: "4722", type: "Authentication", name: "User Account Enabled", description: "Records when a disabled user account is enabled.", fields: ["Target Account", "Subject Account"], maliciousUse: "Detecting reactivation of dormant or previously disabled accounts.", mitre: ["T1098"], icon: Key, color: "text-pink-400" },
  { id: "4725", type: "Authentication", name: "User Account Disabled", description: "Records when a user account is disabled.", fields: ["Target Account", "Subject Account"], maliciousUse: "Detecting account access removal or unauthorized administrative changes.", mitre: ["T1531"], icon: Key, color: "text-pink-400" },
  { id: "4726", type: "Authentication", name: "User Account Deleted", description: "Records deletion of a user account.", fields: ["Target Account", "Subject Account"], maliciousUse: "Detecting destructive identity changes and cleanup of attacker-created accounts.", mitre: ["T1531", "T1070"], icon: Key, color: "text-pink-400" },
  { id: "4732", type: "Authentication", name: "Member Added to Local Security-Enabled Group", description: "Records a member being added to a local security-enabled group.", fields: ["Member", "Target Group", "Subject User", "Computer"], maliciousUse: "Detecting local administrator group abuse and privilege escalation.", mitre: ["T1098", "T1069.001"], icon: Key, color: "text-pink-400" },
  { id: "4768", type: "Authentication", name: "Kerberos Authentication Service Ticket Requested", description: "Records a Kerberos TGT request.", fields: ["Account Name", "Client Address", "Ticket Encryption Type", "Service Name"], maliciousUse: "Detecting unusual Kerberos requests, encryption downgrades and account abuse.", mitre: ["T1558", "T1078"], icon: Key, color: "text-pink-400" },
  { id: "4769", type: "Authentication", name: "Kerberos Service Ticket Requested", description: "Records a Kerberos service ticket request.", fields: ["Account Name", "Client Address", "Service Name", "Ticket Encryption Type"], maliciousUse: "Detecting Kerberoasting patterns and abnormal service-ticket access.", mitre: ["T1558.003"], icon: Key, color: "text-pink-400" },
  { id: "4771", type: "Authentication", name: "Kerberos Pre-Authentication Failed", description: "Records a failed Kerberos pre-authentication attempt.", fields: ["Account Name", "Client Address", "Failure Code", "Pre-Authentication Type"], maliciousUse: "Detecting password guessing, spraying and forged or malformed authentication attempts.", mitre: ["T1110"], icon: Key, color: "text-pink-400" },
  { id: "4776", type: "Authentication", name: "Domain Controller Attempted to Validate Credentials", description: "Records NTLM credential validation by a domain controller.", fields: ["Account Name", "Source Workstation", "Error Code"], maliciousUse: "Detecting password spraying, pass-the-hash and unusual credential validation sources.", mitre: ["T1110", "T1550.002"], icon: Key, color: "text-pink-400" },
  { id: "5145", type: "Object Access", name: "Network Share Object Checked", description: "Records detailed access checks against a network share when object auditing is enabled.", fields: ["Object Type", "Share Name", "Relative Target Name", "Accesses", "Source Address"], maliciousUse: "Detecting sensitive-file discovery and access through administrative shares.", mitre: ["T1021.002", "T1039"], icon: Search, color: "text-teal-400" },
  { id: "5156", type: "Network Connection", name: "Windows Filtering Platform Connection Allowed", description: "Records an allowed network connection through Windows Filtering Platform.", fields: ["Application", "Source Address", "Source Port", "Destination Address", "Destination Port", "Protocol"], maliciousUse: "Correlating outbound C2, lateral movement and exfiltration connections with process identity.", mitre: ["T1071", "T1095", "T1571"], icon: Monitor, color: "text-indigo-400" },
  { id: "5157", type: "Network Connection", name: "Windows Filtering Platform Connection Blocked", description: "Records a network connection blocked by Windows Filtering Platform.", fields: ["Application", "Source Address", "Source Port", "Destination Address", "Destination Port", "Protocol"], maliciousUse: "Detecting repeated failed C2 or lateral movement attempts and policy probing.", mitre: ["T1071", "T1571"], icon: Monitor, color: "text-indigo-400" },
  { id: "1100", type: "System", name: "Event Logging Service Shut Down", description: "Records shutdown of the Windows Event Log service.", fields: ["Subject User", "Process ID", "Process Name"], maliciousUse: "Detecting attempts to create a telemetry gap before destructive or stealth activity.", mitre: ["T1562.002"], icon: ShieldAlert, color: "text-red-500" }
];
