"use client";

import { useMemo, useState } from "react";
import { Copy, Check } from "lucide-react";
import { ToolLayout } from "@/components/tool-layout";

export default function RoeBuilderPage() {
  const [client, setClient] = useState("Client / Organization"); const [scope, setScope] = useState("example.com\n10.10.0.0/16"); const [excluded, setExcluded] = useState("Production databases\nThird-party SaaS"); const [window, setWindow] = useState("2026-09-01 22:00 — 2026-09-02 06:00 UTC"); const [contact, setContact] = useState("security@example.com"); const [copied, setCopied] = useState(false);
  const output = useMemo(() => `# Rules of Engagement\n\nClient: ${client}\nTesting window: ${window}\nEmergency contact: ${contact}\n\n## In scope\n${scope.split(/\r?\n/).filter(Boolean).map(item => `- ${item}`).join("\n") || "- Define authorized assets"}\n\n## Out of scope\n${excluded.split(/\r?\n/).filter(Boolean).map(item => `- ${item}`).join("\n") || "- None specified — confirm before testing"}\n\n## Safety controls\n- Obtain written authorization before testing.\n- No denial-of-service, destructive, persistence or data exfiltration activity.\n- Stop immediately on service instability or sensitive-data exposure.\n- Record timestamps, source addresses, evidence and cleanup actions.\n- Report critical findings through the emergency contact.\n`, [client, contact, excluded, scope, window]);
  const copy = async () => { try { await navigator.clipboard.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { /* clipboard unavailable */ } };
  const field = (label: string, value: string, setValue: (value: string) => void, multiline = false) => <label className="text-xs text-zinc-400">{label}{multiline ? <textarea value={value} onChange={e => setValue(e.target.value)} className="mt-2 min-h-28 w-full resize-y border border-[#242424] bg-black p-3 text-xs text-zinc-200 outline-none focus:border-[#00ff9c] rounded-none" /> : <input value={value} onChange={e => setValue(e.target.value)} className="mt-2 w-full border border-[#242424] bg-black p-3 text-xs text-zinc-200 outline-none focus:border-[#00ff9c] rounded-none" />}</label>;
  return <ToolLayout title="Rules of Engagement Builder" description="Create a bounded, safety-first pentest scope document locally before testing."><div className="grid gap-6 xl:grid-cols-2"><section className="grid gap-4 border border-[#1a1a1a] bg-[#050505] p-4">{field("Client", client, setClient)}{field("Testing window", window, setWindow)}{field("Emergency contact", contact, setContact)}{field("In-scope assets · one per line", scope, setScope, true)}{field("Excluded assets · one per line", excluded, setExcluded, true)}</section><section className="border border-[#1a1a1a] bg-[#050505]"><header className="flex items-center justify-between border-b border-[#1a1a1a] px-4 py-3"><h2 className="text-xs font-bold uppercase tracking-widest text-[#ffb000]">Document</h2><button type="button" onClick={copy} className="flex items-center gap-2 border border-[#242424] px-3 py-2 text-xs text-zinc-400 hover:border-[#00ff9c] hover:text-[#00ff9c] rounded-none">{copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />} {copied ? "Copied" : "Copy"}</button></header><pre className="overflow-auto p-4 font-mono text-xs leading-relaxed text-[#00ff9c]">{output}</pre></section></div></ToolLayout>;
}
