"use client";

import { useState, useMemo, useRef } from "react";
import { ToolLayout } from "@/components/tool-layout";
import { ToolActionButton, ToolConfirmDialog, ToolEmptyState, ToolField, ToolPanel, ToolPanelBody, ToolPanelHeader, ToolPanelTitle } from "@/components/tool-design";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useNotification } from "@/components/notification-provider";
import { Copy, Download, Plus, X } from "lucide-react";
import { GITIGNORE_TEMPLATES } from "@/lib/gitignore-templates";
import { downloadTextFile } from "@/lib/browser-download";

export default function GitignoreGenerator() {
  const [searchTerm, setSearchTerm] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const searchRef = useRef<HTMLInputElement>(null);
  const { notify } = useNotification();

  const availableTemplates = useMemo(() => Object.keys(GITIGNORE_TEMPLATES).filter(name =>
    name.toLowerCase().includes(searchTerm.trim().toLowerCase()) && !selected.includes(name)
  ), [searchTerm, selected]);

  const generatedGitignore = useMemo(() => selected.length
    ? "# Generated by IT_TOOLS\n\n" + selected.map(name => `### ${name} ###\n${GITIGNORE_TEMPLATES[name]}\n`).join("")
    : "", [selected]);

  const copy = async () => {
    if (!generatedGitignore) return;
    try {
      await navigator.clipboard.writeText(generatedGitignore);
      notify("Copied to clipboard");
    } catch {
      notify("Could not copy. Select the generated content and copy it manually.", "error");
    }
  };

  const download = () => {
    if (!generatedGitignore) return;
    try {
      downloadTextFile(generatedGitignore, ".gitignore", "application/octet-stream");
      notify("Download started");
    } catch {
      notify("Could not download. Copy the content into a .gitignore file instead.", "error");
    }
  };

  return (
    <ToolLayout title=".gitignore Generator" description="Combine bundled templates into a .gitignore file. Generated locally, without uploading your project.">
      <div className="grid min-w-0 grid-cols-1 items-start gap-6 lg:grid-cols-2">
        <div className="min-w-0 space-y-6">
          <ToolPanel>
            <ToolPanelHeader><ToolPanelTitle marker="IN">Add Templates</ToolPanelTitle></ToolPanelHeader>
            <ToolPanelBody className="space-y-4">
              <ToolField htmlFor="template-search" label="Search templates" helper="Search by language, framework, editor or operating system.">
                <Input id="template-search" ref={searchRef} value={searchTerm} onChange={event => setSearchTerm(event.target.value)} placeholder="Node, React, Python..."
                  className="rounded-none border-[#1a1a1a] bg-black! text-zinc-300" />
              </ToolField>
              {availableTemplates.length ? (
                <div role="group" aria-label="Available templates" className="flex max-h-60 flex-wrap gap-2 overflow-y-auto p-1">
                  {availableTemplates.map(name => <ToolActionButton key={name} aria-label={`Add ${name}`} onClick={() => {
                    setSelected(current => current.includes(name) ? current : [...current, name]);
                    searchRef.current?.focus();
                  }}><Plus aria-hidden="true" />{name}</ToolActionButton>)}
                </div>
              ) : <ToolEmptyState title="No available templates">Change the search or remove a selected template to add it again.</ToolEmptyState>}
            </ToolPanelBody>
          </ToolPanel>
          <ToolPanel>
            <ToolPanelHeader>
              <ToolPanelTitle marker="SET">Selected ({selected.length})</ToolPanelTitle>
              <ToolConfirmDialog trigger={<ToolActionButton tone="danger" disabled={!selected.length}>Clear All</ToolActionButton>}
                title="Clear all templates?" description="All selected templates and the generated content will be removed." confirmLabel="Clear templates"
                onConfirm={() => setSelected([])} finalFocus={() => selected.length ? true : searchRef.current} />
            </ToolPanelHeader>
            <ToolPanelBody>
              {selected.length ? <div role="group" aria-label="Selected templates" className="flex flex-wrap gap-2">
                {selected.map(name => <ToolActionButton key={name} tone="accent" aria-label={`Remove ${name}`} onClick={() => {
                  setSelected(current => current.filter(item => item !== name));
                  searchRef.current?.focus();
                }}>{name}<X aria-hidden="true" /></ToolActionButton>)}
              </div> : <ToolEmptyState title="No templates selected">Add templates above to generate your file.</ToolEmptyState>}
            </ToolPanelBody>
          </ToolPanel>
        </div>
        <ToolPanel>
          <ToolPanelHeader>
            <ToolPanelTitle marker="OUT">.gitignore Content</ToolPanelTitle>
            <div className="flex flex-wrap gap-2">
              <ToolActionButton disabled={!generatedGitignore} onClick={copy}><Copy aria-hidden="true" />Copy</ToolActionButton>
              <ToolActionButton tone="accent" disabled={!generatedGitignore} onClick={download}><Download aria-hidden="true" />Download</ToolActionButton>
            </div>
          </ToolPanelHeader>
          <ToolPanelBody>
            {generatedGitignore ? <ToolField htmlFor="gitignore-output" label="Generated .gitignore" helper="Templates are combined in selection order. Review the patterns and save the file as .gitignore, including the leading dot.">
              <Textarea id="gitignore-output" value={generatedGitignore} readOnly spellCheck={false} wrap="off"
                className="h-96 field-sizing-fixed resize-y rounded-none border-[#1a1a1a] bg-black! text-zinc-300" />
            </ToolField> : <ToolEmptyState title="Awaiting templates">Select one or more templates to preview, copy or download the file.</ToolEmptyState>}
          </ToolPanelBody>
        </ToolPanel>
      </div>
    </ToolLayout>
  );
}
