import { ArrowDown, ArrowUp, Box, ChevronDown, Copy, Database, Globe, MoreHorizontal, Router, Search, Server, Settings2, Shield, Trash2 } from "lucide-react";

type BoxFamily = "workbench" | "modern" | "retro";
type Theme = "dark" | "light";

const palette = [["Router", Router], ["Server", Server], ["Firewall", Shield], ["Database", Database]] as const;

function DeviceBox({ family, theme, title, meta, icon: Icon, className = "" }: { family: BoxFamily; theme: Theme; title: string; meta: string; icon: typeof Router; className?: string }) {
  const light = theme === "light";
  const familyClass = family === "workbench"
    ? light ? "border-slate-400 bg-white text-slate-900" : "border-[#1a1a1a] bg-[#050505] text-zinc-100"
    : family === "modern"
      ? light ? "rounded-xl border-slate-300 bg-white text-slate-900 shadow-lg" : "rounded-xl border-sky-400/50 bg-[#111827] text-zinc-100 shadow-[0_12px_30px_rgba(0,0,0,0.35)]"
      : light ? "border-slate-700 bg-[#f8f4e8] text-slate-900 shadow-[3px_3px_0_#64748b]" : "border-[#00ff9c]/70 bg-[#06120d] text-[#b7ffd9] shadow-[3px_3px_0_#176b52]";
  const accent = family === "retro" ? (light ? "text-slate-700" : "text-[#00ff9c]") : family === "modern" ? (light ? "text-blue-700" : "text-sky-300") : (light ? "text-slate-600" : "text-[#00ff9c]");
  return <div className={`relative flex h-[82px] w-[150px] flex-col justify-center border p-3 font-mono ${familyClass} ${className}`}>
    {family === "retro" && <div className="pointer-events-none absolute inset-1 border border-dashed border-current opacity-20" />}
    {family === "workbench" && <div className={`absolute inset-x-0 top-0 border-b px-2 py-1 text-[8px] font-bold uppercase tracking-widest ${light ? "border-slate-200 text-slate-500" : "border-[#1a1a1a] text-[#00ff9c]"}`}>[NODE]</div>}
    <div className={family === "workbench" ? "mt-3 flex items-center gap-2" : "flex items-center gap-2"}><Icon className={`h-5 w-5 shrink-0 ${accent}`} strokeWidth={1.5} /><div className="min-w-0"><div className={`truncate text-[11px] font-bold ${family === "workbench" && !light ? "text-[#ffb000]" : ""}`}>{title}</div><div className={`truncate text-[9px] ${light ? "text-slate-500" : "text-zinc-400"}`}>{meta}</div></div></div>
    <div className={`mt-2 text-[8px] uppercase tracking-widest ${light ? "text-emerald-700" : "text-[#72e6b4]"}`}>● active</div>
    <span className={`absolute -left-1.5 top-1/2 h-3 w-3 -translate-y-1/2 border-2 ${light ? "border-white bg-slate-500" : "border-black bg-zinc-400"}`} aria-hidden="true" /><span className={`absolute -right-1.5 top-1/2 h-3 w-3 -translate-y-1/2 border-2 ${light ? "border-white bg-slate-500" : "border-black bg-zinc-400"}`} aria-hidden="true" />
  </div>;
}

function CanvasPreview() {
  return <div className="overflow-x-auto border border-[#1a1a1a] bg-black"><div className="min-w-[760px]"><div className="flex flex-wrap items-center gap-1 border-b border-[#1a1a1a] bg-[#050505] p-2"><button type="button" className="border border-[#2a2a2a] bg-black p-2 text-zinc-400" aria-label="Undo"><Copy className="h-3.5 w-3.5 rotate-180" /></button><button type="button" className="border border-[#2a2a2a] bg-black p-2 text-zinc-400" aria-label="View options"><Settings2 className="h-3.5 w-3.5" /></button><span className="mx-1 h-4 w-px bg-[#1a1a1a]" /><span className="text-[9px] uppercase tracking-widest text-zinc-400">View</span><button type="button" className="border border-[#00ff9c]/40 bg-[#00ff9c]/10 px-2 py-1 text-[9px] uppercase tracking-widest text-[#00ff9c]">Fit</button><button type="button" className="border border-[#2a2a2a] bg-black px-2 py-1 text-[9px] uppercase tracking-widest text-zinc-400">Grid</button></div><div className="grid min-h-[390px] grid-cols-[12rem_1fr]">
    <aside className="border-r border-[#1a1a1a] bg-[#050505] p-3"><div className="mb-3 flex items-center justify-between"><span className="text-[9px] font-bold uppercase tracking-widest text-zinc-400">Node palette</span><span className="text-[9px] text-zinc-400">4/21</span></div><div className="relative mb-3 border border-[#242424] bg-black py-2 pl-7 text-[10px] text-zinc-400"><Search className="absolute left-2 top-1/2 h-3 w-3 -translate-y-1/2" />Find a device…</div><div className="mb-2 flex items-center gap-1 text-[9px] font-bold uppercase tracking-widest text-zinc-400"><ChevronDown className="h-3 w-3" />Network</div><div className="grid grid-cols-2 gap-1.5">{palette.map(([label, Icon]) => <div key={label} className="border border-[#202124] bg-[#0d0e10] p-2 text-center text-[9px] text-zinc-400"><Icon className="mx-auto mb-1 h-4 w-4 text-zinc-400" /><span>{label}</span></div>)}</div><div className="mt-4 border-t border-[#1a1a1a] pt-3"><div className="mb-2 text-[9px] font-bold uppercase tracking-widest text-zinc-400">Selection</div><div className="flex gap-1"><button type="button" className="border border-[#2a2a2a] p-1.5 text-zinc-400" aria-label="Move up"><ArrowUp className="h-3 w-3" /></button><button type="button" className="border border-[#2a2a2a] p-1.5 text-zinc-400" aria-label="Move down"><ArrowDown className="h-3 w-3" /></button><button type="button" className="border border-red-900/60 p-1.5 text-red-400" aria-label="Delete selected"><Trash2 className="h-3 w-3" /></button></div></div></aside>
    <div className="relative overflow-auto bg-[#0a0a0a]" style={{ backgroundImage: "radial-gradient(#242424 0.7px, transparent 0.7px)", backgroundSize: "16px 16px" }}><div className="relative h-[360px] w-[760px]"><svg className="pointer-events-none absolute inset-0 h-full w-full" viewBox="0 0 760 360" aria-label="Aligned topology cables"><path d="M220 176 H300" fill="none" stroke="#00ff9c" strokeWidth="2" /><path d="M450 176 H505 V116 H560" fill="none" stroke="#94a3b8" strokeWidth="1.5" /><path d="M450 176 H505 V276 H560" fill="none" stroke="#fbbf24" strokeWidth="1.5" strokeDasharray="5 4" /><text x="238" y="165" fill="#00ff9c" fontSize="9">trunk</text><text x="477" y="266" fill="#fbbf24" fontSize="9">backup</text></svg><div className="absolute left-7 top-7 h-[280px] w-[465px] border border-dashed border-[#00ff9c]/50 bg-[#00ff9c]/[0.04] p-3"><div className="text-[9px] font-bold uppercase tracking-widest text-[#00ff9c]">Office 1</div><div className="mt-1 text-[8px] text-zinc-400">Group container · zone: lan</div></div><div className="absolute left-[70px] top-[135px]"><DeviceBox family="workbench" theme="dark" icon={Router} title="Core Router" meta="10.0.0.1 · VLAN 10" /></div><div className="absolute left-[300px] top-[135px]"><DeviceBox family="workbench" theme="dark" icon={Box} title="Access Switch" meta="10.0.1.2 · VLAN 20" /></div><div className="absolute left-[560px] top-[75px]"><DeviceBox family="retro" theme="dark" icon={Server} title="Web Server" meta="10.0.1.10" /></div><div className="absolute left-[560px] top-[235px]"><DeviceBox family="retro" theme="dark" icon={Database} title="DB Server" meta="10.0.1.11" /></div><div className="absolute right-4 top-4 border border-[#2a2a2a] bg-black p-1"><button type="button" aria-label="Open canvas menu" className="text-zinc-400"><MoreHorizontal className="h-4 w-4" /></button><div className="absolute right-0 top-7 z-10 w-36 border border-[#2a2a2a] bg-[#080808] p-1 text-[9px] text-zinc-400"><div className="px-2 py-1">Edit properties</div><div className="flex items-center gap-2 px-2 py-1"><Copy className="h-3 w-3" />Duplicate</div><div className="flex items-center gap-2 px-2 py-1 text-red-400"><Trash2 className="h-3 w-3" />Delete</div></div></div><div className="absolute bottom-3 left-3 border border-[#1a1a1a] bg-black/90 px-2 py-1 text-[9px] text-zinc-400">4 nodes · 3 links · <span className="text-amber-300">1 issue</span></div></div></div>
  </div></div></div>;
}

export function DiagramDesignDemo() {
  return <div className="space-y-4"><CanvasPreview /><div className="grid gap-3 md:grid-cols-3">{(["workbench", "modern", "retro"] as const).map(family => <div key={family} className="border border-[#1a1a1a] bg-[#050505] p-3"><p className="mb-3 text-[9px] font-bold uppercase tracking-widest text-zinc-400">{family === "workbench" ? "01 / workbench canonical" : family === "modern" ? "02 / modern product" : "03 / retro terminal"}</p><div className="grid gap-2"><DeviceBox family={family} theme="dark" icon={family === "modern" ? Shield : family === "retro" ? Database : Router} title={family === "workbench" ? "Router" : family === "modern" ? "Firewall" : "Archive DB"} meta="10.0.0.1 · active" className="w-full" /><DeviceBox family={family} theme="light" icon={Globe} title="Light export" meta="print / report mode" className="w-full" /></div><p className="mt-3 text-[9px] leading-relaxed text-zinc-400">Dark and light are paired variants. Workbench is the product default; modern and retro are opt-in styles.</p></div>)}</div></div>;
}
