import { ArrowDown, ArrowUp, BatteryCharging, Bell, Cable, Check, ChevronDown, CircleAlert, CircleCheck, CircleX, Clock3, CloudUpload, Database, Download, FileCode2, FileJson, FileText, FolderOpen, HardDrive, Info, Laptop, Network, Router, Server, Shield, Table2, Upload, Wifi, X } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { FileExchangeDemo } from "./FileExchangeDemo";

function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "success" | "attention" | "error" | "shortcut" }) {
  const styles = { neutral: "border-[#2a2a2a] text-zinc-400", success: "border-[#176b52] text-[#9fffd1]", attention: "border-[#795c19] text-[#fbbf24]", error: "border-[#8f2435] text-[#ff9aa9]", shortcut: "border-[#2a2a2a] bg-[#111111] text-zinc-500" };
  return <span className={`inline-flex min-h-5 items-center border px-1.5 text-[9px] font-bold uppercase tracking-wider ${styles[tone]}`}>{children}</span>;
}

function CodeField({ language, children }: { language: string; children: string }) {
  const lines = children.split("\n");
  return <div className="border border-[#1a1a1a] bg-black"><div className="flex items-center justify-between border-b border-[#1a1a1a] bg-[#0a0a0a] px-3 py-2"><span className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-widest text-zinc-500"><FileCode2 className="h-3.5 w-3.5 text-[#00ff9c]" />{language}</span><div className="flex gap-1"><button type="button" className="border border-[#2a2a2a] p-1 text-zinc-500" aria-label="Copy code"><FileText className="h-3 w-3" /></button><button type="button" className="border border-[#2a2a2a] p-1 text-zinc-500" aria-label="Download code"><Download className="h-3 w-3" /></button></div></div><pre className="overflow-x-auto p-3 text-[10px] leading-relaxed text-zinc-300"><code>{lines.map((line, index) => <span key={`${index}-${line}`} className="block"><span className="mr-4 inline-block w-5 select-none text-right text-zinc-700">{index + 1}</span><span className={line.includes("#") || line.includes("//") ? "text-zinc-600" : line.includes("=") || line.includes(":") ? "text-[#9fffd1]" : "text-zinc-300"}>{line}</span></span>)}</code></pre></div>;
}

export function PatternShowcase() {
  return <div className="space-y-6">
    <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Modal triggers</h3><p className="text-[10px] leading-relaxed text-zinc-600">Import and export are actions that open a focused modal, rather than permanently occupying the main toolbar.</p><FileExchangeDemo /></div>
    <div className="grid gap-6 xl:grid-cols-2">
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Badges and direct access</h3><div className="flex flex-wrap items-center gap-2"><span className="flex items-center gap-2 text-xs text-zinc-300"><Bell className="h-3.5 w-3.5 text-zinc-500" />Notifications <Badge tone="attention">3</Badge></span><span className="flex items-center gap-2 text-xs text-zinc-300"><FolderOpen className="h-3.5 w-3.5 text-zinc-500" />Recent <Badge>12</Badge></span><span className="flex items-center gap-2 text-xs text-zinc-300"><Shield className="h-3.5 w-3.5 text-[#00ff9c]" />Favorite <Badge tone="success">Pinned</Badge></span><Badge tone="shortcut">⌘ K</Badge></div><div className="flex flex-wrap gap-2 border-t border-[#1a1a1a] pt-3"><Badge tone="success">Ready</Badge><Badge tone="attention">3 issues</Badge><Badge tone="error">Blocked</Badge><button type="button" className="inline-flex items-center gap-2 border border-[#1a1a1a] bg-[#050505] px-3 py-1.5 text-[10px] font-bold uppercase tracking-widest text-zinc-400 hover:border-[#00ff9c] hover:text-[#00ff9c]">Show more <ChevronDown className="h-3 w-3" /></button></div></div>
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Panels and inline states</h3><div className="flex items-start gap-2 border border-sky-500/40 bg-sky-500/5 p-3 text-xs text-sky-200"><Info className="mt-0.5 h-4 w-4 shrink-0" />Information stays beside the relevant content.</div><div className="flex items-start gap-2 border border-[#795c19] bg-[#795c19]/5 p-3 text-xs text-[#fbbf24]"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" />Attention asks for review without blocking.</div><div className="flex items-start gap-2 border border-[#8f2435] bg-[#8f2435]/5 p-3 text-xs text-[#ff9aa9]"><CircleX className="mt-0.5 h-4 w-4 shrink-0" />Error explains the correction required.</div><div className="flex items-start gap-2 border border-[#176b52] bg-[#176b52]/5 p-3 text-xs text-[#9fffd1]"><CircleCheck className="mt-0.5 h-4 w-4 shrink-0" />Success confirms a completed local operation.</div></div>
    </div>

    <div className="grid gap-6 xl:grid-cols-2">
      <div className="space-y-4 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Modal and file exchange</h3><div className="relative min-h-[30rem] overflow-hidden border border-[#1a1a1a] bg-black"><div className="absolute inset-0 bg-black/70" /><div className="absolute left-1/2 top-1/2 max-h-[calc(100%-2rem)] w-[min(32rem,calc(100%-2rem))] -translate-x-1/2 -translate-y-1/2 overflow-y-auto border border-[#2a2a2a] bg-[#080808] shadow-2xl"><header className="flex items-center justify-between border-b border-[#1a1a1a] px-4 py-3"><span className="text-xs font-bold uppercase tracking-widest text-[#ffb000]">Import diagram</span><button type="button" aria-label="Close modal" className="text-zinc-500 hover:text-white"><X className="h-4 w-4" /></button></header><div className="space-y-3 p-4"><p className="text-[10px] leading-relaxed text-zinc-500">Modal content is focused, bounded and dismissible with the close button or Escape.</p><div className="border border-dashed border-[#176b52] bg-[#176b52]/5 p-6 text-center"><CloudUpload className="mx-auto mb-2 h-5 w-5 text-[#00ff9c]" /><p className="text-[10px] text-zinc-300">Drop JSON here or browse</p><p className="mt-1 text-[9px] text-zinc-600">Max 2 MB · local only</p></div><div className="flex justify-end gap-2"><button type="button" className="border border-[#2a2a2a] px-3 py-1.5 text-[10px] text-zinc-400">Cancel</button><button type="button" className="border border-[#00ff9c]/40 bg-[#00ff9c]/10 px-3 py-1.5 text-[10px] text-[#00ff9c]">Import</button></div></div></div></div><div className="flex flex-wrap gap-2"><button type="button" className="flex items-center gap-2 border border-[#1a1a1a] px-3 py-2 text-[10px] text-zinc-400"><Upload className="h-3 w-3" />Import</button><button type="button" className="flex items-center gap-2 border border-[#1a1a1a] px-3 py-2 text-[10px] text-zinc-400"><Download className="h-3 w-3" />Export</button></div></div>
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Drop files</h3><div className="flex min-h-36 flex-col items-center justify-center border border-dashed border-[#2a2a2a] bg-black p-4 text-center hover:border-[#00ff9c]/60"><CloudUpload className="mb-3 h-6 w-6 text-zinc-500" /><p className="text-xs text-zinc-300">Drop a file here</p><p className="mt-1 text-[10px] text-zinc-600">or choose a file from this device</p><button type="button" className="mt-3 border border-[#1a1a1a] px-3 py-1.5 text-[10px] text-[#00ff9c]">Browse files</button></div><div className="flex items-center justify-between border border-[#1a1a1a] bg-black p-2 text-[10px]"><span className="flex items-center gap-2 text-zinc-400"><FileJson className="h-3.5 w-3.5 text-[#00ff9c]" />diagram.json · 128 KB</span><span className="text-[#9fffd1]">Ready</span></div></div>
    </div>

    <div className="space-y-4 border border-[#1a1a1a] bg-[#050505] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Code fields by content type</h3><div className="flex gap-1"><Badge>YAML</Badge><Badge>JS</Badge><Badge>PY</Badge><Badge>SH</Badge></div></div><div className="grid gap-4 lg:grid-cols-2"><CodeField language="YAML">{"apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: app-config\ndata:\n  LOG_LEVEL: info"}</CodeField><CodeField language="JavaScript">{"export function normalize(value) {\n  // Keep transformation local\n  return value.trim();\n}"}</CodeField><CodeField language="Python">{"def validate_target(value: str) -> bool:\n    return bool(value.strip())\n\nprint(validate_target(target))"}</CodeField><CodeField language="PowerShell / Shell">{"$target = \"server-01\"\nGet-Service -ComputerName $target\n# Review before executing"}</CodeField></div><div className="border-t border-[#1a1a1a] pt-3 text-[10px] leading-relaxed text-zinc-600">Code fields use no-wrap by default with horizontal scroll, line numbers, language label, copy/download actions and syntax-oriented colours. Long prose fields, such as runbook descriptions, use a normal wrapping textarea instead.</div></div>

    <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Timeline</h3><div className="relative space-y-4 border-l border-[#2a2a2a] pl-5"><div className="relative"><span className="absolute -left-[1.35rem] top-1 h-2 w-2 border border-black bg-[#00ff9c]" /><p className="text-[9px] text-zinc-600">09:42:18 UTC · <span className="text-[#00ff9c]">INFO</span></p><p className="mt-1 text-xs text-zinc-300">Backup window started</p></div><div className="relative"><span className="absolute -left-[1.35rem] top-1 h-2 w-2 border border-black bg-[#fbbf24]" /><p className="text-[9px] text-zinc-600">09:48:03 UTC · <span className="text-[#fbbf24]">WARN</span></p><p className="mt-1 text-xs text-zinc-300">Throughput below target</p></div><div className="relative"><span className="absolute -left-[1.35rem] top-1 h-2 w-2 border border-black bg-[#f87171]" /><p className="text-[9px] text-zinc-600">09:51:44 UTC · <span className="text-[#f87171]">ERROR</span></p><p className="mt-1 text-xs text-zinc-300">Replication paused</p></div></div><div className="flex items-center gap-2 text-[10px] text-zinc-600"><Clock3 className="h-3.5 w-3.5" />Use timestamp + severity + event; avoid one large card per event.</div></div>
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Stats panel</h3><div className="grid grid-cols-2 gap-px border border-[#1a1a1a] bg-[#1a1a1a] sm:grid-cols-4"><div className="bg-[#050505] p-3"><span className="text-[9px] uppercase tracking-widest text-zinc-600">Packets</span><strong className="mt-2 block text-xl text-zinc-100">12,480</strong><span className="text-[9px] text-[#9fffd1]">+4.2%</span></div><div className="bg-[#050505] p-3"><span className="text-[9px] uppercase tracking-widest text-zinc-600">Flows</span><strong className="mt-2 block text-xl text-zinc-100">842</strong><span className="text-[9px] text-zinc-600">local capture</span></div><div className="bg-[#050505] p-3"><span className="text-[9px] uppercase tracking-widest text-zinc-600">Alerts</span><strong className="mt-2 block text-xl text-[#fbbf24]">3</strong><span className="text-[9px] text-[#fbbf24]">review</span></div><div className="bg-[#050505] p-3"><span className="text-[9px] uppercase tracking-widest text-zinc-600">Dropped</span><strong className="mt-2 block text-xl text-[#f87171]">0.4%</strong><span className="text-[9px] text-zinc-600">within limit</span></div></div><svg className="h-20 w-full border border-[#1a1a1a] bg-black" viewBox="0 0 400 80" preserveAspectRatio="none" aria-label="Example traffic graph"><path d="M0 60 L35 48 L70 54 L105 24 L140 38 L175 30 L210 44 L245 20 L280 28 L315 14 L350 26 L400 8" fill="none" stroke="#00ff9c" strokeWidth="2" /><path d="M0 60 L35 48 L70 54 L105 24 L140 38 L175 30 L210 44 L245 20 L280 28 L315 14 L350 26 L400 8 V80 H0 Z" fill="#00ff9c" opacity="0.08" /></svg><div className="flex items-center justify-between text-[9px] text-zinc-600"><span>10:00</span><span>10:30</span><span>11:00</span></div></div>
    </div>

    <div className="grid gap-6 xl:grid-cols-2"><div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Checkbox patterns</h3><label className="flex items-center gap-3 text-xs text-zinc-300"><Checkbox defaultChecked />Selected / binary</label><label className="flex items-center gap-3 text-xs text-zinc-300"><span className="grid size-4 place-items-center border border-[#00ff9c] bg-[#00ff9c] text-black"><Check className="h-3 w-3" /></span>Indeterminate / partial</label><label className="flex items-center gap-3 text-xs text-zinc-300"><span className="size-4 border border-[#8f2435]" />Destructive confirmation</label><label className="flex items-center gap-3 text-xs text-zinc-300"><span className="size-4 border border-[#2a2a2a]" />Disabled / unavailable</label><p className="text-[10px] text-zinc-600">Use a checkbox for independent choices; use tabs or radios for mutually exclusive modes.</p></div><div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Icon set</h3><div className="grid grid-cols-3 gap-2 text-[9px] text-zinc-500 sm:grid-cols-6">{[[Router, "router"], [Server, "server"], [Shield, "security"], [Database, "storage"], [Wifi, "wireless"], [Laptop, "endpoint"], [HardDrive, "disk"], [BatteryCharging, "ups"], [Network, "network"], [Cable, "link"], [ArrowUp, "up"], [ArrowDown, "down"]].map(([Icon, label]) => { const Glyph = Icon as typeof Router; return <div key={String(label)} className="border border-[#1a1a1a] bg-black p-2 text-center"><Glyph className="mx-auto mb-1 h-4 w-4 text-zinc-400" /><span>{String(label)}</span></div>; })}</div></div></div>

    <div className="border border-[#1a1a1a] bg-[#050505] p-4"><div className="flex items-center justify-between border-b border-[#1a1a1a] pb-3"><h3 className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]"><Table2 className="h-3.5 w-3.5" />Tables</h3><span className="text-[9px] text-zinc-600">horizontal scroll at narrow widths</span></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[38rem] text-left text-[10px]"><thead className="border-b border-[#2a2a2a] text-zinc-500"><tr><th className="px-3 py-2 uppercase tracking-widest">Asset</th><th className="px-3 py-2 uppercase tracking-widest">Type</th><th className="px-3 py-2 uppercase tracking-widest">Status</th><th className="px-3 py-2 uppercase tracking-widest">Updated</th></tr></thead><tbody><tr className="border-b border-[#111] text-zinc-300"><td className="px-3 py-2">edge-router-01</td><td className="px-3 py-2 text-zinc-500">Router</td><td className="px-3 py-2 text-[#9fffd1]">Active</td><td className="px-3 py-2 text-zinc-600">2 min ago</td></tr><tr className="text-zinc-300"><td className="px-3 py-2">backup-node-02</td><td className="px-3 py-2 text-zinc-500">Storage</td><td className="px-3 py-2 text-[#fbbf24]">Review</td><td className="px-3 py-2 text-zinc-600">8 min ago</td></tr></tbody></table></div></div>
  </div>;
}
