import { ArrowDown, ArrowUp, BatteryCharging, Bell, Cable, Check, ChevronDown, Clock3, Database, FolderOpen, HardDrive, Laptop, Network, Router, Server, Shield, Table2, Wifi } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { ToolBadge, ToolCodeField, ToolFileDropzone, ToolStat, ToolStatGrid, ToolStatus, ToolTimeline } from "@/components/tool-design";
import { FileExchangeDemo } from "./FileExchangeDemo";

export function PatternShowcase() {
  return <div className="space-y-6">
    <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Modal triggers</h3><p className="text-[10px] leading-relaxed text-zinc-400">Import and export are actions that open a focused modal, rather than permanently occupying the main toolbar.</p><FileExchangeDemo /></div>
    <div className="grid gap-6 xl:grid-cols-2">
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Badges and direct access</h3><div className="flex flex-wrap items-center gap-2"><span className="flex items-center gap-2 text-xs text-zinc-300"><Bell className="h-3.5 w-3.5 text-zinc-400" />Notifications <ToolBadge tone="attention">3</ToolBadge></span><span className="flex items-center gap-2 text-xs text-zinc-300"><FolderOpen className="h-3.5 w-3.5 text-zinc-400" />Recent <ToolBadge>12</ToolBadge></span><span className="flex items-center gap-2 text-xs text-zinc-300"><Shield className="h-3.5 w-3.5 text-[#00ff9c]" />Favorite <ToolBadge tone="success">Pinned</ToolBadge></span><ToolBadge tone="shortcut">⌘ K</ToolBadge></div><div className="flex flex-wrap gap-2 border-t border-[#1a1a1a] pt-3"><ToolBadge tone="success">Ready</ToolBadge><ToolBadge tone="attention">3 issues</ToolBadge><ToolBadge tone="error">Blocked</ToolBadge><button type="button" className="inline-flex items-center gap-2 border border-[#1a1a1a] bg-[#050505] px-3 py-1.5 text-[10px] font-bold uppercase tracking-widest text-zinc-400 hover:border-[#00ff9c] hover:text-[#00ff9c]">Show more <ChevronDown className="h-3 w-3" /></button></div></div>
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Panels and inline states</h3><ToolStatus tone="info">Information stays beside relevant content.</ToolStatus><ToolStatus tone="attention">Attention asks for review without blocking.</ToolStatus><ToolStatus tone="error">Error explains required correction.</ToolStatus><ToolStatus tone="success">Success confirms a completed local operation.</ToolStatus></div>
    </div>

    <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">File exchange</h3><p className="text-[10px] leading-relaxed text-zinc-400">The same dropzone accepts tool-specific formats, limits and validation callbacks without duplicating drag, keyboard or file-state behavior.</p><ToolFileDropzone accept=".json,.csv,.txt" acceptedFormats="JSON, CSV or text" maxSizeBytes={2 * 1024 * 1024} label="Drop a supported file here" /></div>

    <div className="space-y-4 border border-[#1a1a1a] bg-[#050505] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Code fields by content type</h3><div className="flex gap-1"><ToolBadge>YAML</ToolBadge><ToolBadge>JS</ToolBadge><ToolBadge>PY</ToolBadge><ToolBadge>SH</ToolBadge></div></div><div className="grid gap-4 lg:grid-cols-2"><ToolCodeField language="YAML" code={"apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: app-config\ndata:\n  LOG_LEVEL: info"} filename="example.yaml" /><ToolCodeField language="JavaScript" code={"export function normalize(value) {\n  // Keep transformation local\n  return value.trim();\n}"} filename="example.js" /><ToolCodeField language="Python" code={"def validate_target(value: str) -> bool:\n    return bool(value.strip())\n\nprint(validate_target(target))"} filename="example.py" /><ToolCodeField language="PowerShell / Shell" code={"$target = \"server-01\"\nGet-Service -ComputerName $target\n# Review before executing"} filename="example.ps1" /></div><div className="border-t border-[#1a1a1a] pt-3 text-[10px] leading-relaxed text-zinc-400">Code fields use no-wrap by default with horizontal scroll, line numbers, language label, copy/download actions and syntax-oriented colours. Long prose fields, such as runbook descriptions, use a normal wrapping textarea instead.</div></div>

    <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Timeline</h3><ToolTimeline items={[{ id: "started", timestamp: "09:42:18 UTC", severity: "INFO", title: "Local operation started", tone: "success" }, { id: "review", timestamp: "09:48:03 UTC", severity: "WARN", title: "Value needs review", tone: "attention" }, { id: "failed", timestamp: "09:51:44 UTC", severity: "ERROR", title: "Operation paused", tone: "error" }]} /><div className="flex items-center gap-2 text-[10px] text-zinc-400"><Clock3 className="h-3.5 w-3.5" />Use timestamp + severity + event; avoid one large card per event.</div></div>
      <div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Stats panel</h3><ToolStatGrid><ToolStat label="Items" value="12,480" context="+4.2%" tone="success" /><ToolStat label="Groups" value="842" context="local data" /><ToolStat label="Warnings" value="3" context="review" tone="attention" /><ToolStat label="Errors" value="0.4%" context="within limit" tone="error" /></ToolStatGrid><svg className="h-20 w-full border border-[#1a1a1a] bg-black" viewBox="0 0 400 80" preserveAspectRatio="none" aria-label="Example result trend"><path d="M0 60 L35 48 L70 54 L105 24 L140 38 L175 30 L210 44 L245 20 L280 28 L315 14 L350 26 L400 8" fill="none" stroke="#00ff9c" strokeWidth="2" /><path d="M0 60 L35 48 L70 54 L105 24 L140 38 L175 30 L210 44 L245 20 L280 28 L315 14 L350 26 L400 8 V80 H0 Z" fill="#00ff9c" opacity="0.08" /></svg><div className="flex items-center justify-between text-[9px] text-zinc-400"><span>10:00</span><span>10:30</span><span>11:00</span></div></div>
    </div>

    <div className="grid gap-6 xl:grid-cols-2"><div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Checkbox patterns</h3><label className="flex items-center gap-3 text-xs text-zinc-300"><Checkbox defaultChecked />Selected / binary</label><label className="flex items-center gap-3 text-xs text-zinc-300"><span className="grid size-4 place-items-center border border-[#00ff9c] bg-[#00ff9c] text-black"><Check className="h-3 w-3" /></span>Indeterminate / partial</label><label className="flex items-center gap-3 text-xs text-zinc-300"><span className="size-4 border border-[#8f2435]" />Destructive confirmation</label><label className="flex items-center gap-3 text-xs text-zinc-300"><span className="size-4 border border-[#2a2a2a]" />Disabled / unavailable</label><p className="text-[10px] text-zinc-400">Use a checkbox for independent choices; use tabs or radios for mutually exclusive modes.</p></div><div className="space-y-3 border border-[#1a1a1a] bg-[#050505] p-4"><h3 className="text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]">Icon set</h3><div className="grid grid-cols-3 gap-2 text-[9px] text-zinc-400 sm:grid-cols-6">{[[Router, "router"], [Server, "server"], [Shield, "security"], [Database, "storage"], [Wifi, "wireless"], [Laptop, "endpoint"], [HardDrive, "disk"], [BatteryCharging, "ups"], [Network, "network"], [Cable, "link"], [ArrowUp, "up"], [ArrowDown, "down"]].map(([Icon, label]) => { const Glyph = Icon as typeof Router; return <div key={String(label)} className="border border-[#1a1a1a] bg-black p-2 text-center"><Glyph className="mx-auto mb-1 h-4 w-4 text-zinc-400" /><span>{String(label)}</span></div>; })}</div></div></div>

    <div className="border border-[#1a1a1a] bg-[#050505] p-4"><div className="flex items-center justify-between border-b border-[#1a1a1a] pb-3"><h3 className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-[#00ff9c]"><Table2 className="h-3.5 w-3.5" />Tables</h3><span className="text-[9px] text-zinc-400">horizontal scroll at narrow widths</span></div><div role="region" aria-label="Example result table" tabIndex={0} className="mt-3 overflow-x-auto"><table className="w-full min-w-[38rem] text-left text-[10px]"><thead className="border-b border-[#2a2a2a] text-zinc-400"><tr><th className="px-3 py-2 uppercase tracking-widest">Asset</th><th className="px-3 py-2 uppercase tracking-widest">Type</th><th className="px-3 py-2 uppercase tracking-widest">Status</th><th className="px-3 py-2 uppercase tracking-widest">Updated</th></tr></thead><tbody><tr className="border-b border-[#111] text-zinc-300"><td className="px-3 py-2">edge-router-01</td><td className="px-3 py-2 text-zinc-400">Router</td><td className="px-3 py-2 text-[#9fffd1]">Active</td><td className="px-3 py-2 text-zinc-400">2 min ago</td></tr><tr className="text-zinc-300"><td className="px-3 py-2">backup-node-02</td><td className="px-3 py-2 text-zinc-400">Storage</td><td className="px-3 py-2 text-[#fbbf24]">Review</td><td className="px-3 py-2 text-zinc-400">8 min ago</td></tr></tbody></table></div></div>
  </div>;
}
